version: "3.5"

services:
  app:
    container_name: nutracker-api
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      - mongo.host=mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - /home/ec2-user/dev/nutracker-db:/data/db
    ports:
      - "27017:27017"
