version: "2"
services:
  app:
    container_name: nutracker-api
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/home/ec2-user/dev/nutracker-db
    ports:
      - "27017:27017"
