version: "2"

services:
  app:
    container_name: nutracker-api
    restart: always
    build: .
    expose:
      - 8080
    ports:
      - "8080:8080"
  # legacy
  # links:
  #    - mongo
    environment:
      - mongo.host=mongo-host-container
  mongo:
    container_name: mongo-host-container
    image: mongo
    volumes:
      - /home/ec2-user/dev/nutracker-db:/data/db
    ports:
      - "27017:27017"
